"""Add access_token to user table

Revision ID: 08ec63b0a032
Revises: 43e04ac477f4
Create Date: 2025-03-07 16:38:26.312851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ec63b0a032'
down_revision: Union[str, None] = '43e04ac477f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'access_token')
    # ### end Alembic commands ###
