"""Сделаны url и phone nullable

Revision ID: 0b54f408e828
Revises: e90589b644ce
Create Date: 2025-04-07 15:12:53.244992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b54f408e828'
down_revision: Union[str, None] = 'e90589b644ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_networks', sa.Column('phone', sa.String(), nullable=True))
    op.alter_column('social_networks', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('social_networks', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('social_networks', 'phone')
    # ### end Alembic commands ###
