"""Remove lesson_id, add description to materials

Revision ID: 1b3e2ff7d0d5
Revises: 08ec63b0a032
Create Date: 2025-03-18 19:10:58.573475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b3e2ff7d0d5'
down_revision: Union[str, None] = '08ec63b0a032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('description', sa.Text(), nullable=True))
    op.drop_constraint('materials_lesson_id_fkey', 'materials', type_='foreignkey')
    op.drop_column('materials', 'lesson_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('materials_lesson_id_fkey', 'materials', 'lesson', ['lesson_id'], ['id'])
    op.drop_column('materials', 'description')
    # ### end Alembic commands ###
