"""Добавлена связь пользователей и материалов

Revision ID: 31582fd49e8c
Revises: 1b3e2ff7d0d5
Create Date: 2025-03-19 16:53:03.896716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31582fd49e8c'
down_revision: Union[str, None] = '1b3e2ff7d0d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'materials', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_column('materials', 'user_id')
    # ### end Alembic commands ###
