"""fix foreign key references

Revision ID: 4a939ed379df
Revises: 8ecb6d1d4626
Create Date: 2025-03-21 03:41:29.807251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a939ed379df'
down_revision: Union[str, None] = '8ecb6d1d4626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('materials_user_id_fkey', 'materials', type_='foreignkey')
    op.create_foreign_key(None, 'materials', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key('materials_user_id_fkey', 'materials', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
