"""Swap chat_id to user_id in User model

Revision ID: 8c825f1e5fc1
Revises: b2f5a038701b
Create Date: 2025-02-03 19:09:53.079877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c825f1e5fc1'
down_revision: Union[str, None] = 'b2f5a038701b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_chat_id_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['user_id'])
    op.drop_column('user', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_chat_id_key', 'user', ['chat_id'])
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
