"""Удаление teacher и lesson

Revision ID: 8ecb6d1d4626
Revises: e3f90d0281ec
Create Date: 2025-03-20 18:09:12.400451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ecb6d1d4626'
down_revision: Union[str, None] = 'e3f90d0281ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
