"""Add foreign key to Lesson table

Revision ID: b2f5a038701b
Revises: 
Create Date: 2025-02-03 19:04:49.603807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f5a038701b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lesson', 'teacher', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lesson', type_='foreignkey')
    op.drop_column('lesson', 'teacher_id')
    # ### end Alembic commands ###
