"""Упрощение моделей и их количества

Revision ID: e3f90d0281ec
Revises: 31582fd49e8c
Create Date: 2025-03-20 18:05:50.341817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3f90d0281ec'
down_revision: Union[str, None] = '31582fd49e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher')
    op.drop_table('enrollments')
    op.drop_table('lesson')
    op.drop_table('progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name='progress_lesson_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='progress_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='progress_pkey')
    )
    op.create_table('lesson',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('lesson_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('max_students', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name='lesson_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='lesson_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('enrollments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('registered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name='enrollments_lesson_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='enrollments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='enrollments_pkey')
    )
    op.create_table('teacher',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qualification', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='teacher_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='teacher_pkey'),
    sa.UniqueConstraint('user_id', name='teacher_user_id_key')
    )
    # ### end Alembic commands ###
